title: "One tasty pizza paper"
subtitle: "A cheesy template"
author: "Jack Zezula"
date: "July 2021"
numbersections: yes
toc: yes
pagestyle: "headings"
colorlinks: yes
linkstyle: "bold"
link-citations: yes
reference-section-title: "References"
fontfamily: charter